// <auto-generated />
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(SkolaDbContext))]
    [Migration("20260419110028_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Kurs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Kursnamn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LarareId")
                        .HasColumnType("int");

                    b.Property<int>("Poang")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LarareId");

                    b.ToTable("Kurser");
                });

            modelBuilder.Entity("Domain.Entities.Larare", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Namn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Larare");
                });

            modelBuilder.Entity("Domain.Entities.Kurs", b =>
                {
                    b.HasOne("Domain.Entities.Larare", null)
                        .WithMany("Kurser")
                        .HasForeignKey("LarareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Larare", b =>
                {
                    b.Navigation("Kurser");
                });
#pragma warning restore 612, 618
        }
    }
}
